version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: node.js.Dockerfile
    ports:
      - "3000:3000"

  mongo-db:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
