name: syntax

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [$NODE_VERSION]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm ci

    - name: Lint code
      run: |
        npx eslint .

    - name: Test code
      run: |
        npm test
        
        
